In [1]:
import pandas as pd
path = "./csv/test/"

In [2]:
def summary_df(path):
    df = pd.read_csv(path)
    return df["predict"].value_counts(normalize = True)[:10]*100

In [3]:
summary_df(path + "result_Seq2seq.csv")

あー           35.261490
あ            15.649762
そうなんですか       8.914422
そう            5.467512
はい            5.348653
そうですよね        5.190174
そうなんですね       3.724247
あーそうなんですね     3.169572
あそうなんですね      2.694136
そうですか         2.535658
Name: predict, dtype: float64

In [4]:
summary_df(path + "result_transformer.csv")

あー           10.488959
うーん           9.424290
そうですね         5.717666
あはい           4.219243
へえ            4.100946
あそうなんですか      3.746057
あ             3.509464
あーそうなんですね     3.430599
そうですよね        3.233438
あそうなんですね      3.075710
Name: predict, dtype: float64

In [5]:
summary_df(path + "result_bert_embedded_seq2seq.csv")

あー           63.919558
ああ            4.652997
そうですよね        3.706625
そうですね         2.878549
あーそうなんですね     2.523659
はー            2.168770
えー            1.813880
あーそうですかー      1.735016
そうなんですね       1.695584
あーそうですねー      1.537855
Name: predict, dtype: float64

In [6]:
summary_df(path + "result_bert_embedded_transformer.csv")

あー           22.949527
うーん           8.201893
あーそうなんですね     7.255521
そうですね         5.086751
あ             4.337539
あーそうなんですか     3.746057
ああ            3.509464
あはい           2.996845
へえ            2.602524
そうですよね        1.813880
Name: predict, dtype: float64

In [7]:
pd.read_csv('./data/train.csv')['output'].value_counts(normalize = True)[:10] * 100

あー       5.08
うーん      4.70
へえ       2.60
ああ       2.28
あ        2.28
そうですね    2.04
あはい      1.84
へー       1.70
あっ       1.50
はー       1.22
Name: output, dtype: float64

In [8]:
path = "./data/test.tsv"

In [9]:
input, output = [], []
with open(path, mode = 'r', encoding = "utf-8") as f:
    for f_list in f.readlines():
        # print(f_list)
        tmp = f_list.split('\t')
        input.append(tmp[0])
        output.append(tmp[1].replace("\n", ""))

In [10]:
df = pd.DataFrame({'input':input, 'output':output})

In [11]:
df

                              input         output
0                     石蹴りっていうんですかあの  あっはい石蹴りやりましたね
1                           そのリリアンと       あそうなんですね
2                    えー筆はまー置きましたけども  あっおいてしまったんですか
3                  自分の運も良かったんでしょうけど         そうですよね
4     乗り換えてからまた乗り換えなきゃいけない大江戸線だけであの      また乗り換えですか
...                             ...            ...
1208                      そういう場所を探し              あ
1209                  遊びに来るようになりました   そーですかー3回も4回も
1210       やっておりましたので本が好きでいつもおうちの中で              あ
1211           結構自分ちに帰りたがらないっていうことが             へー
1212                仕事をしてた時は本は自分で購入          ええええあ

[1213 rows x 2 columns]

In [12]:
df.to_csv(path.replace('tsv', 'csv'), index = False)

In [13]:
import MeCab

In [38]:
def check_conv(df):
    for _ in range(10):
        index = random.randint(0, len(df))
        tmp_df = s2s_df.iloc[index]
        print(tmp_df['input'], tmp_df['predict'], tmp_df['predict'] in tmp_df['answer'])

In [39]:
path = "./csv/test/"
s2s_df = pd.read_csv(path + "result_Seq2seq.csv")
Bs2s_df = pd.read_csv(path + "result_bert_embedded_seq2seq.csv")
tf_df = pd.read_csv(path + "result_transformer.csv")
Btf_df = pd.read_csv(path + "result_bert_embedded_transformer.csv")

In [40]:
import random

In [41]:
check_conv(s2s_df)

アメリカに出張してくれと あー True
一等地と言われていたところだですが そうなんですね True
スーパーのでごめんねって言って そうですよね False
もう33年もまえからまー友達っていうかあの私のところが塾をしていたものですから あー True
缶を蹴ると あー False
ことを覚えておりますけども あー True
それはあのにじんでくるので文章を書いているうちに あー False
えーそういう意味ではそのこの先生がですね空手は教えるけど決して暴力を振るうことはまかりならんよということでこれを守れなければ教えないということでそれを守っておりますので未だに そうですよね False
ただし そうなんですか False
まーこの年になると仲間がねまー逝っちゃったんで あー True

In [46]:
check_conv(Bs2s_df)

その そうなんですか False
とてもあの試験なんかいいよって言ったら逆に後輩に諭されて あ True
いうことであのーそれをずーっと続けておりまして そうなんですね False
えー駒回しですね駒回しとか はい True
えー駒回しですね駒回しとか はい True
できなくなったり そうなんですか True
珍しいお菓子と言って手紙がはを入れ一緒に送ってきてくださった あー True
新しい家に入ることなく亡くなったのが あーそうなんですね True
駅まで歩きまして あ True
だと思います そうですか True

In [43]:
check_conv(tf_df)

功労賞で表彰するからと あー False
それがアメリカで あー False
戦争中でしたですから あー False
そんな感じです そうなんですか False
朝早く行って両方の あー False
八十八か所見つけていますが はい True
のま神様みたいなものも あー False
えー妻とのおー出会ったときが一番嬉しかった あ True
あー そうなんですか False
4年の所を優待生で3年間で あー False

In [45]:
check_conv(Btf_df)

あとまー最近 はい False
えーどうしたら そう False
鬼怒川温泉の旅行に行きました時 あー True
親指と人差し指で そうなんですね False
そういう簡単な遊びでしたねあとは あー True
事を感じていました あー True
は逆の方へは行きまして あー True
いうことで そうなんですね False
そして登りたいという人を一緒に連れて行きたいです あー True
ま逆に大変なことはいっぱいあると思いますけども孫たちも そうですよね False

In [33]:
s2s_df

,Unnamed: 0,input,answer,predict
0,0,15分前に事務所に着きました,"['あーそーなんですねー', 'そうなんですね', 'あーはい', 'あ計画通りで', 'あ...",あ
1,1,16年間その先生にお世話になって,"['十六年もですか', 'あー長い間', '長いですね']",凄い
2,2,1回も行っておりませんので,"['あーそうなんですね', 'あー遠のいてしまったんですね', 'そうなんですか', 'うー...",あー
3,3,1番っていわれるとわたくしはちょっと戸惑ってしまいます,"['うーん', 'あーそーですか', 'あはいそうなんですか']",あそうなんですね
4,4,20代だいぶ昔の話ですけれども20代の後半に仲良し3人組で女性ですがあのまー安い宿を使って軽...,"['あ', 'いいですね', 'あー']",あー
...,...,...,...,...
2531,2531,魚獲りをいたしました,"['はーそーですかー', 'あっ魚釣りはい', 'そうですね', 'あーはい', 'あはい魚...",あー
2532,2532,魚釣りをやったり,"['魚釣り', 'あー', 'ふーんはいはい', 'ああ釣りをしたり', 'へーいいですね']",あー
2533,2533,鳥を捕まえるというそんな,"['鳥をですか', 'あはいそうですね', 'へえ', 'へえ', '捕まえるんですね', ...",そう
2534,2534,麹町番長の,['そうなんですね'],そうなんですか
2535,2535,麻雀をするとか,"['あーおおおお', '麻雀もおやりになるんですね', 'あはい', 'あーあはいはい', ...",あー